const logos1 = new Map([
    ["Facebook", "https://www.facebook.com/images/fb_icon_325x325.png"],
    ["Google", "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"],
    ["Instagram", "https://www.instagram.com/static/images/ico/favicon-192.png/68d99ba29cc8.png"],
    ["Twitter", "https://abs.twimg.com/favicons/twitter.ico"],
    ["LinkedIn", "https://static-exp1.licdn.com/sc/h/br/a32w2yzk6pwv8bjkk0jso9xj6"],
    ["TikTok", "https://s16.tiktokcdn.com/musical/resource/img/logo_x2_v3.png"],
    ["Snapchat", "https://www.snapchat.com/favicon.ico"],
    ["Pinterest", "https://www.pinterest.com/assets/misc/favicon-5e7d5af5d5ed5df710c786e5bbea6305.ico"],
    ["YouTube", "https://www.youtube.com/s/desktop/bf996a5d/img/favicon_144.png"],
    ["Gmail", "https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_default_1x_r2.png"],
    ["Yahoo! Mail", "https://www.yahoo.com/favicon.ico"],
    ["Outlook", "https://c.s-microsoft.com/favicon.ico?v2"],
    ["ProtonMail", "https://protonmail.com/favicon.ico"],
    ["Zoho Mail", "https://www.zoho.com/mail/favicon.ico"],
    ["Mail.com", "https://www.mail.com/assets/img/app-logo_mail_com.ico"],
    ["AOL Mail", "https://www.aol.com/favicon.ico"],
    ["GMX Mail", "https://sso.gmx.com/favicon.ico"],
    ["Binance", "https://bin.bnbstatic.com/static/images/common/favicon.ico"],
    ["Coinbase", "https://www.coinbase.com/assets/favicon-96x96.png?rev=5bdb9b6"],
    ["Kraken", "https://www.kraken.com/img/favicons/apple-touch-icon.png"],
    ["Gemini", "https://gemini.com/wp-content/themes/gemini/dist/images/favicon/favicon-32x32.png"],
    ["Bitfinex", "https://www.bitfinex.com/assets/icons/favicon-32x32.png?v=3"],
    ["Bitstamp", "https://www.bitstamp.net/s/apple-touch-icon.png"],
    ["Bittrex", "https://bittrex.com/Content/themes/bittrex2018/img/favicon/apple-touch-icon.png"],
    ["Poloniex", "https://poloniex.com/images/favicons/favicon.ico"],
    ["Akbank", "https://www.akbank.com/SiteAssets/img/favicon.ico"],
    ["Garanti BBVA", "https://bbva.webfileretail.com/favicon.ico"],
    ["Yapı Kredi", "https://www.yapikredi.com.tr/_layouts/15/YapiKredi.SharePoint.Delegate/Search/Branding/images/favicon.ico"],
    ["İşbank", "https://www.isbank.com.tr/TR/_catalogs/masterpage/images/logo-isbank.ico"],
    ["Ziraat Bankası", "https://www.ziraatbank.com.tr/Themes/ZiraatBank/assets/images/faviocn.ico"],
    ["Finansbank", "https://www.qnbfinansbank.com/favicon.ico"],
    ["HSBC Turkey", "https://www.hsbc.com.tr//assets/images/favicon.ico"],
    ["TEB", "https://www.teb.com.tr/Portals/0/favicon.ico"],
    ["Denizbank", "https://web.denizbank.com/favicon.ico"]
]);

const logos2 = new Map([
    ["Kuveyt Türk", "https://www.kuveytturk.com.tr/KuveytturkSiteAssets/favicons/favicon.ico"],
    ["Vakıfbank", "https://www.vakifbank.com.tr/SiteAssets/img/favicon.ico"],
    ["ING Turkey", "https://assets.ingbank.com.tr/Content/themes/base/assets/images/favicons/favicon.ico"],
    ["Alternatifbank", "https://www.abank.com.tr/_partials/k-favicon.ico"],
    ["Şekerbank", "https://www.sekerbank.com.tr/favicon.ico"],
    ["Abank", "https://www.abank.com.tr/_partials/k-favicon.ico"],
    ["QNB Finansbank", "https://www.qnbfinansbank.com/favicon.ico"],
    ["Odea Bank", "https://www.odeabank.com.tr/StaticFiles?FileType=TIF&FileVersion=0&DocId=4881&Locale=tr-TR&Source=Original"],
    ["Halkbank", "https://www.halkbank.com.tr/themes/halkbanknew/assets/images/favicon.ico"],
    ["Türkiye Finans", "https://www.turkiyefinans.com.tr/favicon.ico"],
    ["AnadoluBank", "https://s3.eu-central-1.amazonaws.com/cdn.anadolubank.com.tr/WebSites/Portal/Images/fav-icon/favicon-32x32.png"],
    ["ICBC Turkey", "https://www.icbc.com.tr/favicon.ico"],
    ["Aktifbank", "https://www.aktifbank.com.tr/favicon.ico"],
    ["TurkishBank", "https://www.turkishbank.com.tr/favicon.ico"],
    ["Fibabanka", "https://static.fibabanka.com.tr/assets/img/favicons/favicon.ico?v=2"],
    ["PttBank", "https://www.pttbank.com.tr/Content/img/pttbank-favicon.ico"],
    ["Citibank Turkey", "https://www.online.citibank.com.tr/favicon.ico"],
    ["Enpara", "https://www.enpara.com/favicons/favicon-32x32.png"],
    ["Papara", "https://cdn.papara.com/papara-com/images/favicon.ico"],
    ["Paycell", "https://www.paycell.com.tr/Content/assets/img/favicon.ico"],
    ["Paytr", "https://www.paytr.com/Content/themes/base/img/favicon.ico"],
    ["PayU", "https://www.payu.com.tr/favicon.ico"],
    ["PayPal", "https://www.paypal.com/favicon.ico"],
    ["Hepsiburada", "https://www.hepsiburada.com/favicon.ico"],
    ["n11", "https://www.n11.com/favicon.ico"],
    ["Gittigidiyor", "https://s3.eu-central-1.amazonaws.com/gittigidiyor-site/gittigidiyor-favicon.png"],
    ["Trendyol", "https://cdn.dsmcdn.com/web/favicon.ico"],
    ["Getir", "https://cdn.getir.com/misc/fe-favicons/getir/favicon.ico"],
    ["Banabi", "https://www.banabi.com.tr/public/desktop/img/favicons/apple-icon-57x57.png"],
    ["Migros Sanal Market", "https://assets.migroskurumsal.com/market/production/1.0.425/static/images/icons/icon-96x96.png"],
    ["CarrefourSA Hemen", "https://www.carrefoursa.com/favicon.ico"],
    ["Glovo", "https://glovoapp.com/theme/img/glovo/favicon.png"],
    ["Yemeksepeti", "https://cdn.yemeksepeti.com/App_Themes/Main/images/favicon.ico"],
    ["Domino's Pizza Turkey", "https://www.dominos.com.tr/Content/Images/favico-32x32.png"],
    ["Burger King Türkiye", "https://www.burgerking.com.tr/favicon.ico"],
    ["McDonald's Türkiye", "https://www.mcdonalds.com.tr/content/dam/turkey/icons/favicons/favicon-32x32.png"]
]);

export const appLogos = new Map([...logos1, ...logos2]);